services:
  landing:
    container_name: landing
    build:
      context: .
      dockerfile: ./Dockerfile
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./certs:/etc/nginx/certs:ro
      - ./certbot-webroot:/var/www/certbot
    restart: unless-stopped