server {
    listen 80;
    server_name zik-zikurrat.dev www.zik-zikurrat.dev;

    # Let's Encrypt challenge — ВЫШЕ редиректа, иначе уйдёт в https
    location /.well-known/acme-challenge/ {
        root /var/www/certbot;
    }

    location / {
        return 301 https://$host$request_uri;
    }
}

server {
    listen 443 ssl;
    server_name zik-zikurrat.dev www.zik-zikurrat.dev;

    ssl_certificate     /etc/nginx/certs/fullchain.pem;
    ssl_certificate_key /etc/nginx/certs/privkey.pem;

    # challenge и здесь — LE ходит по редиректу на https
    location /.well-known/acme-challenge/ {
        root /var/www/certbot;
    }

    root /usr/share/nginx/html;
    index index.html;

    location / {
        try_files $uri $uri/ /index.html;
    }
}